### ISSUE TITLE
Input shape of Soft DTW

### ISSUE THREAD

**Issue by v-nhandt21** [Maghoumi/DeepNAG#1]
Hi, I just reach your paper, Could I have a question the what is the input shape of x and y in this line https://github.com/Maghoumi/DeepNAG/blob/1f6a16aa2ba029ee4e8dfa2536d2b1c2ea3eeda0/models/hausdorff_distance.py#L140

Because I also try Soft DTW, but it uses too much memory, what are the batch size and GPU resources you use in this project?

Thank you!

**Comment by Maghoumi** [comment]
I added the following `print` statements right at the start of this function:

```
....
# Initialize the result to inf
result = torch.ones(x.shape[0], device=x.device) * np.inf
print(x.shape)
print(y.shape)
exit(0)
```

Here's the output:
```
torch.Size([4096, 64, 63])
torch.Size([4096, 64, 63])
```

As you can see, even with our small dataset and a default batch size of 64, these tensors end up becoming fairly large. The reason is that for pair-wise Hausdorff distance calculation between predictions and GT, `64x64` computations are needed (need to calculate the Hausdorff distance between every prediction and GT sample).

**Comment by v-nhandt21** [comment]
> I added the following `print` statements right at the start of this function:
> 
> ```
> ....
> # Initialize the result to inf
> result = torch.ones(x.shape[0], device=x.device) * np.inf
> print(x.shape)
> print(y.shape)
> exit(0)
> ```
> 
> Here's the output:
> 
> ```
> torch.Size([4096, 64, 63])
> torch.Size([4096, 64, 63])
> ```
> 
> As you can see, even with our small dataset and a default batch size of 64, these tensors end up becoming fairly large. The reason is that for pair-wise Hausdorff distance calculation between predictions and GT, `64x64` computations are needed (need to calculate the Hausdorff distance between every prediction and GT sample).

Yes, I have tested and got the problem, this is my test with maximum batch-size for each frame:
![image](https://user-images.githubusercontent.com/36092323/139611379-077ecd17-1a9e-4b61-8327-6a17e671996c.png)


Have you reached the method from google which is custom softDTW
https://arxiv.org/pdf/2103.14574.pdf

![image](https://user-images.githubusercontent.com/36092323/139611179-6234c142-3669-458b-86bb-05522cc2a3a1.png)
