### ISSUE TITLE
Kinect v2

### ISSUE THREAD

**Issue by Nurul9927** [Maghoumi/DeepNAG#2]
Hello can this project use by kinect v2?

**Comment by Maghoumi** [comment]
As noted in the [README file](https://github.com/Maghoumi/DeepNAG#kinect-gestures), the sample dataset (JK2017) is actually a Kinect dataset (and it is in fact Kinect v2).

**Comment by Nurul9927** [comment]
Thank you, sorry for bothering, can you help me with this error
